name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./CollaborativeTextEditor_backend
          file: ./CollaborativeTextEditor_backend/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/cte_backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./CollaborativeTextEditor_frontend
          file: ./CollaborativeTextEditor_frontend/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/cte_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker images
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cte_backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/cte_frontend:latest

      - name: Deploy with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
