name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend Docker image
        run: |
          echo "Building backend Docker image"
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/cte_backend:latest ./CollaborativeTextEditor_backend --progress plain --load
          docker images

      - name: Push backend Docker image
        run: |
          echo "Pushing backend Docker image"
          docker push ghcr.io/${{ github.repository_owner }}/cte_backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build frontend Docker image
        run: |
          echo "Building frontend Docker image"
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/cte_frontend:latest ./CollaborativeTextEditor_frontend --progress plain --load
          docker images

      - name: Push frontend Docker image
        run: |
          echo "Pushing frontend Docker image"
          docker push ghcr.io/${{ github.repository_owner }}/cte_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/cte_backend:latest
          docker pull ghcr.io/${{ github.repository_owner }}/cte_frontend:latest

      - name: Deploy with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
